# Generated by Django 5.2.12 on 2026-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_key", models.CharField(max_length=100, unique=True)),
                ("config_group", models.CharField(max_length=64)),
                ("config_value", models.TextField(blank=True, default="")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "字符串"),
                            ("int", "整数"),
                            ("bool", "布尔值"),
                        ],
                        default="string",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["config_group", "config_key"],
            },
        ),
    ]
