# Generated by Django 5.2.12 on 2026-03-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_systemconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=1024)),
                ("file_type", models.CharField(default="unknown", max_length=32)),
                ("source_module", models.CharField(default="unknown", max_length=64)),
                ("file_size", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
